### ISSUE TITLE
Multiple levels aren't handled

### ISSUE THREAD

**Issue by vanga** [amestsantim/pycspro#4]
Hi,

I don't know if this is a new format or something, I have a DCF file that has multiple levels in it. The JSON structure and code seem to have been designed to only work with one Level as the value of `Level` is a dictionary.

Relations also aren't handled right now.

I don't know much about the configparser library or the machine library. But, I am able to improvise and get things working for both of the above issues by just adding the necessary *_received functions and appending levels.

Curious to know your thoughts.
https://gist.github.com/vanga/4a196516209712d77f188e3d699fd299 this the DCF file of a hierarchical dataset that I am testing for your reference.

**Comment by amestsantim** [comment]
Yes, you are correct on both points. I never implemented support for multiple levels and relations.
This has to do with the fact that I originally wrote this because it was needed for a particular dictionary and that dictionary had neither multiple levels nor relations.

Unfortunately, I do not have time to invest in adding those functionalities as we no longer need this library but a pull request would be welcome!

Thanks!
